### ISSUE TITLE
False positive - Binance.com in browsers

### ISSUE THREAD

**Issue by nmhung1985** [CitizenXVIL/Hosts#1]
Hi, I'm using your host file in Adhell3. Currently, if your host file is enabled, Binance.com (a crypto exchange) is totally broken in browsers, just shows html code and texts.

Their native app seemed fine as it let me login but I saw some images were not displayed, and have not tried any trading though.

Hope you would take a look at this. Thanks.

**Comment by CitizenXVIL** [comment]
Oh, sorry. I didn't expect anyone to use the issue area here. I'll take a look at this!

**Comment by CitizenXVIL** [comment]
I believe I found the cause. The domain "nbstatic.com" from AdGuard's simplified domain list blocks "ex.bnbstatic.com" which binance.com uses. This happens because AH appends a wildcard at the start of all domains, so "nbstatic.com" in my list actually becomes "*nbstatic.com".

I'll replace nbstatic.com with *.nbstatic.com which should solve the issue and still block what AdGuard's list intended to block.
